<?xml version="1.0" encoding="UTF-8"?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is JAX-WS RI 2.2.9-b130926.1035 svn-revision#5f6196f2b90e9460065a4c2f4e30e065b245e51e. -->
<xs:schema xmlns:tns="http://core.nip.nibss/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"

           targetNamespace="http://core.nip.nibss/">

    <xs:element name="accountblock" type="tns:accountblock"></xs:element>

    <xs:element name="accountblockResponse" type="tns:accountblockResponse"></xs:element>

    <xs:element name="accountunblock" type="tns:accountunblock"></xs:element>

    <xs:element name="accountunblockResponse" type="tns:accountunblockResponse"></xs:element>

    <xs:element name="adjustNIPSettings" type="tns:adjustNIPSettings"></xs:element>

    <xs:element name="adjustNIPSettingsResponse" type="tns:adjustNIPSettingsResponse"></xs:element>

    <xs:element name="amountblock" type="tns:amountblock"></xs:element>

    <xs:element name="amountblockResponse" type="tns:amountblockResponse"></xs:element>

    <xs:element name="amountunblock" type="tns:amountunblock"></xs:element>

    <xs:element name="amountunblockResponse" type="tns:amountunblockResponse"></xs:element>

    <xs:element name="balanceenquiry" type="tns:balanceenquiry"></xs:element>

    <xs:element name="balanceenquiryResponse" type="tns:balanceenquiryResponse"></xs:element>

    <xs:element name="financialinstitutionlist" type="tns:financialinstitutionlist"></xs:element>

    <xs:element name="financialinstitutionlistResponse" type="tns:financialinstitutionlistResponse"></xs:element>

    <xs:element name="ftackcreditrequest" type="tns:ftackcreditrequest"></xs:element>

    <xs:element name="ftackcreditrequestResponse" type="tns:ftackcreditrequestResponse"></xs:element>

    <xs:element name="fundtransferAdvice_dc" type="tns:fundtransferAdvice_dc"></xs:element>

    <xs:element name="fundtransferAdvice_dcResponse" type="tns:fundtransferAdvice_dcResponse"></xs:element>

    <xs:element name="fundtransferAdvice_dd" type="tns:fundtransferAdvice_dd"></xs:element>

    <xs:element name="fundtransferAdvice_ddResponse" type="tns:fundtransferAdvice_ddResponse"></xs:element>

    <xs:element name="fundtransfersingleitem_dc" type="tns:fundtransfersingleitem_dc"></xs:element>

    <xs:element name="fundtransfersingleitem_dcResponse" type="tns:fundtransfersingleitem_dcResponse"></xs:element>

    <xs:element name="fundtransfersingleitem_dd" type="tns:fundtransfersingleitem_dd"></xs:element>

    <xs:element name="fundtransfersingleitem_ddResponse" type="tns:fundtransfersingleitem_ddResponse"></xs:element>

    <xs:element name="mandateadvice" type="tns:mandateadvice"></xs:element>

    <xs:element name="mandateadviceResponse" type="tns:mandateadviceResponse"></xs:element>

    <xs:element name="nameenquirysingleitem" type="tns:nameenquirysingleitem"></xs:element>

    <xs:element name="nameenquirysingleitemResponse" type="tns:nameenquirysingleitemResponse"></xs:element>

    <xs:element name="privateAdjustmentOfSettings" type="tns:privateAdjustmentOfSettings"></xs:element>

    <xs:element name="privateAdjustmentOfSettingsResponse" type="tns:privateAdjustmentOfSettingsResponse"></xs:element>

    <xs:element name="txnstatusquerysingleitem" type="tns:txnstatusquerysingleitem"></xs:element>

    <xs:element name="txnstatusquerysingleitemResponse" type="tns:txnstatusquerysingleitemResponse"></xs:element>

    <xs:complexType name="amountunblock">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="amountunblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="adjustNIPSettings">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="adjustNIPSettingsResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="financialinstitutionlist">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="financialinstitutionlistResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="txnstatusquerysingleitem">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="txnstatusquerysingleitemResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="amountblock">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="amountblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="privateAdjustmentOfSettings">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="privateAdjustmentOfSettingsResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nameenquirysingleitem">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nameenquirysingleitemResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountblock">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_dc">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_dcResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_dd">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_ddResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="balanceenquiry">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="balanceenquiryResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ftackcreditrequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ftackcreditrequestResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountunblock">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountunblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mandateadvice">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mandateadviceResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_dd">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_ddResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_dc">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_dcResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>