<?xml version="1.0" encoding="UTF-8"?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is JAX-WS RI 2.2.9-b130926.1035 svn-revision#5f6196f2b90e9460065a4c2f4e30e065b245e51e. -->
<xs:schema xmlns:tns="http://core.nip.nibss/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"

           targetNamespace="http://core.nip.nibss/">

    <xs:element name="accountblockRequest" type="xs:string"></xs:element>

    <xs:element name="accountblockResponse" type="xs:string"></xs:element>

    <xs:element name="accountunblockRequest" type="xs:string"></xs:element>

    <xs:element name="accountunblockResponse" type="xs:string"></xs:element>

    <xs:element name="amountblockRequest" type="xs:string"></xs:element>

    <xs:element name="amountblockResponse" type="xs:string"></xs:element>

    <xs:element name="amountunblockRequest" type="xs:string"></xs:element>

    <xs:element name="amountunblockResponse" type="xs:string"></xs:element>

    <xs:element name="balanceenquiryRequest" type="xs:string"></xs:element>

    <xs:element name="balanceenquiryResponse" type="xs:string"></xs:element>

    <xs:element name="financialinstitutionlistRequest" type="xs:string"></xs:element>

    <xs:element name="financialinstitutionlistResponse" type="xs:string"></xs:element>

    <xs:element name="fundtransferAdvice_dcRequest" type="xs:string"></xs:element>

    <xs:element name="fundtransferAdvice_dcResponse" type="xs:string"></xs:element>

    <xs:element name="fundtransferAdvice_ddRequest" type="xs:string"></xs:element>

    <xs:element name="fundtransferAdvice_ddResponse" type="xs:string"></xs:element>

    <xs:element name="fundtransfersingleitem_dcRequest" type="xs:string"></xs:element>

    <xs:element name="fundtransfersingleitem_dcResponse" type="xs:string"></xs:element>

    <xs:element name="fundtransfersingleitem_ddRequest" type="xs:string"></xs:element>

    <xs:element name="fundtransfersingleitem_ddResponse" type="xs:string"></xs:element>

    <xs:element name="mandateadviceRequest" type="xs:string"></xs:element>

    <xs:element name="mandateadviceResponse" type="xs:string"></xs:element>

    <xs:element name="nameenquirysingleitemRequest" type="xs:string"></xs:element>

    <xs:element name="nameenquirysingleitemResponse" type="xs:string"></xs:element>

    <xs:element name="txnstatusquerysingleitemRequest" type="xs:string"></xs:element>

    <xs:element name="txnstatusquerysingleitemResponse" type="xs:string"></xs:element>
</xs:schema>