<?xml version="1.0" encoding="UTF-8"?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is JAX-WS RI 2.2.9-b130926.1035 svn-revision#5f6196f2b90e9460065a4c2f4e30e065b245e51e. -->
<xs:schema xmlns:tns="http://core.nip.nibss/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"

           targetNamespace="http://core.nip.nibss/">

    <xs:element name="accountblockRequest" type="tns:accountblockRequest"></xs:element>

    <xs:element name="accountblockResponse" type="tns:accountblockResponse"></xs:element>

    <xs:element name="accountunblockRequest" type="tns:accountunblockRequest"></xs:element>

    <xs:element name="accountunblockResponse" type="tns:accountunblockResponse"></xs:element>

    <xs:element name="amountblockRequest" type="tns:amountblockRequest"></xs:element>

    <xs:element name="amountblockResponse" type="tns:amountblockResponse"></xs:element>

    <xs:element name="amountunblockRequest" type="tns:amountunblockRequest"></xs:element>

    <xs:element name="amountunblockResponse" type="tns:amountunblockResponse"></xs:element>

    <xs:element name="balanceenquiryRequest" type="tns:balanceenquiryRequest"></xs:element>

    <xs:element name="balanceenquiryResponse" type="tns:balanceenquiryResponse"></xs:element>

    <xs:element name="financialinstitutionlistRequest" type="tns:financialinstitutionlistRequest"></xs:element>

    <xs:element name="financialinstitutionlistResponse" type="tns:financialinstitutionlistResponse"></xs:element>

    <xs:element name="fundtransferAdvice_dcRequest" type="tns:fundtransferAdvice_dcRequest"></xs:element>

    <xs:element name="fundtransferAdvice_dcResponse" type="tns:fundtransferAdvice_dcResponse"></xs:element>

    <xs:element name="fundtransferAdvice_ddRequest" type="tns:fundtransferAdvice_ddRequest"></xs:element>

    <xs:element name="fundtransferAdvice_ddResponse" type="tns:fundtransferAdvice_ddResponse"></xs:element>

    <xs:element name="fundtransfersingleitem_dcRequest" type="tns:fundtransfersingleitem_dcRequest"></xs:element>

    <xs:element name="fundtransfersingleitem_dcResponse" type="tns:fundtransfersingleitem_dcResponse"></xs:element>

    <xs:element name="fundtransfersingleitem_ddRequest" type="tns:fundtransfersingleitem_ddRequest"></xs:element>

    <xs:element name="fundtransfersingleitem_ddResponse" type="tns:fundtransfersingleitem_ddResponse"></xs:element>

    <xs:element name="mandateadviceRequest" type="tns:mandateadviceRequest"></xs:element>

    <xs:element name="mandateadviceResponse" type="tns:mandateadviceResponse"></xs:element>

    <xs:element name="nameenquirysingleitemRequest" type="tns:nameenquirysingleitemRequest"></xs:element>

    <xs:element name="nameenquirysingleitemResponse" type="tns:nameenquirysingleitemResponse"></xs:element>

    <xs:element name="txnstatusquerysingleitemRequest" type="tns:txnstatusquerysingleitemRequest"></xs:element>

    <xs:element name="txnstatusquerysingleitemResponse" type="tns:txnstatusquerysingleitemResponse"></xs:element>

    <xs:complexType name="amountunblockRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="amountunblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="financialinstitutionlistRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="financialinstitutionlistResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="txnstatusquerysingleitemRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="txnstatusquerysingleitemResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="amountblockRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="amountblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nameenquirysingleitemRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nameenquirysingleitemResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountblockRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_dcRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_dcResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_ddRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransfersingleitem_ddResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="balanceenquiryRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="balanceenquiryResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountunblockRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accountunblockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mandateadviceRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mandateadviceResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_ddRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_ddResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_dcRequest">
        <xs:sequence>
            <xs:element name="request" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fundtransferAdvice_dcResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>