#app
app.environment=prod


#Database settings



nip.senderBankCode=999157
nip.dateTimeFormat=yyMMddHHmmss
nip.sessionIdLength=12
nip.ssmPrivateKeyPath=ssm/ga_private_key.key
nip.ssmPublicKeyPath=ssm/nibss_public_key.key
nip.ssmPasswordKey=techonodevInnovate
#ignore NIBSS encryption so that we can test for NIP Inward, should be set to FALSE in production
nip.ignoreEncryption=false
nip.bankUrl=http://localhost:7222