#app
app.environment=prod
app.jwtToken=$2a$10$lugD64NjkZjUGq4tFfMfYeaLeA
app.event.queue.name=nip
#Database settings



nip.senderBankCode=999157
nip.ssmPrivateKeyPath=ssm/ga_private_key.key
nip.ssmPublicKeyPath=ssm/nibss_public_key.key
nip.ssmPasswordKey=techonodevInnovate
#ignore NIBSS encryption so that we can test for NIP Inward, should be set to FALSE in production
nip.ignoreEncryption=false
nip.bankUrl=https://pgs.globalaccelerex.com

#wait time in seconds before we send a tsq
nip.tsqWaitTime =60

#access control service
ac.baseUrl=https://pgs.globalaccelerex.com
ac.username=nip
ac.password={ssm-parameter}pgs.prod.accesscontrol.password