#app
app.environment=development
app.name=nipmiddleware



server.port = 7222


#Database settings


##spring cloud setting 
#cloud.aws.credentials.accessKey=
#cloud.aws.credentials.secretKey=
cloud.aws.credentials.instanceProfile=true
#cloud.aws.region.auto=true
cloud.aws.region.static=eu-west-1


nip.baseUrl=http://196.6.103.10:
