#app
app.environment=prod
app.jwtToken=$2a$10$lugD64NjkZjUGq4tFfMfYeaLeA
app.event.queue.name=nip
app.baseUrl = https://pgs.globalaccelerex.com


#Database settings
spring.datasource.password={ssm-parameter}pgs.prod.db.password



nip.webServiceUrl=http://41.58.130.134:8086/NIPWS/NIPInterface
nip.tsqUrl=http://196.6.103.233:88/NIPWS/NIPTSQInterface
nip.soapActionUrl=http://core.nip.nibss/NIPInterface
nip.ssmPrivateKeyPath=ssm/ga_private_key.key
nip.ssmPublicKeyPath=ssm/nibss_public_key.key
nip.ssmPasswordKey=tdi-prod

#access control service
ac.baseUrl=https://pgs.globalaccelerex.com
ac.username=nip
ac.password={ssm-parameter}pgs.prod.accesscontrol.password

nip.bankUrl=https://pgs.globalaccelerex.com





