#app
spring.datasource.password={ssm-parameter}nip-service.staging.db.password
spring.datasource.username=nip


nip.bankUrl=https://pgs-sandbox.globalaccelerex.com
app.baseUrl = https://pgs-sandbox.globalaccelerex.com





nip.webServiceUrl=http://172.21.8.230:8803/NIPWS/NIPInterface
nip.tsqUrl=http://172.21.8.230:8804/NIPWS/NIPTSQInterface
#ignore NIBSS encryption so that we can test for NIP Inward, should be set to FALSE in dev/production
nip.ignoreEncryption= false 




