#app
app.environment=development
app.name=nipmiddleware
app.jwtToken=$2a$10$lugD64NjkZjUGq4tFfMfYeaLeA
app.event.queue.name=nip_staging
app.baseUrl = http://localhost

#access control service
ac.baseUrl =https://sandbox.globalaccelerex.com
ac.username=lanre
ac.password=lanre


server.port = 7222


#Database settings
spring.datasource.url=jdbc:mysql://localhost:3306/nip?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.validation-query=SELECT 1
spring.datasource.test-on-borrow=true
spring.datasource.test-on-return=true



spring.data.jpa.repositories.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

##spring cloud setting
#cloud.aws.credentials.accessKey=
#cloud.aws.credentials.secretKey=
cloud.aws.credentials.instanceProfile=true
#cloud.aws.region.auto=true
cloud.aws.region.static=eu-west-1



nip.webServiceUrl=http://127.0.0.1:3036/NIPWS/NIPInterface
nip.tsqUrl=http://127.0.0.1:3037/NIPWS/NIPTSQInterface
nip.soapActionUrl=http://core.nip.nibss/NIPInterface


# Global Accelerex Config
ga.privateKeyPath=ssm/ga/dev/ga_private_key.key
ga.publicKeyPath=ssm/ga/dev/nibss_public_key.key
ga.passwordKey=techonodevInnovate
ga.institutionCode = 999157

ga.bankName = Global Accelerex 

# SLS Config
sls.privateKeyPath=ssm/sls/dev/sls_private_dev.key
sls.publicKeyPath=ssm/sls/dev/NIBSS_PUBLIC_KEY.KEY
sls.passwordKey=tdi-sls-dev
sls.institutionCode = 999186
sls.baseUrl =
sls.bankName = SLS


#ignore NIBSS encryption so that we can test for NIP Inward, should be set to FALSE in production
nip.ignoreEncryption= true 


nip.bankUrl=http://localhost:7222

