#app
app.environment=dev
app.baseUrl=http://196.6.103.10:86/NIPWS/NIPInterface
app.tsqUrl=http://196.6.103.10:88/NIPWS/NIPTSQInterface

spring.datasource.password={ssm-parameter}nip-service.staging.db.password
spring.datasource.username=nip


nip.senderBankCode=999157
nip.dateTimeFormat=yyMMddHHmmss
nip.sessionIdLength=12
nip.ssmPrivateKeyPath=ssm/ga_private_key.key
nip.ssmPublicKeyPath=ssm/nibss_public_key.key
nip.ssmPasswordKey=techonodevInnovate
#ignore NIBSS encryption so that we can test for NIP Inward, should be set to FALSE in production
nip.ignoreEncryption=true
nip.bankUrl=https://pgs-sandbox.globalaccelerex.com

#wait time in milliseconds before we send a tsq
nip.tsqWaitTime = 60000


