#app
spring.datasource.password={ssm-parameter}nip-service.staging.db.password
spring.datasource.username=nip


nip.bankUrl=https://pgs-sandbox.globalaccelerex.com
app.baseUrl = https://pgs-sandbox.globalaccelerex.com




