#app
app.environment=development
app.name=nipmiddleware
app.baseUrl=http://127.0.0.1:3036/NIPWS/NIPInterface
app.tsqUrl=http://127.0.0.1:88/NIPWS/NIPTSQInterface
app.soapActionUrl=http://core.nip.nibss/NIPInterface


server.port = 7222


#Database settings
spring.datasource.url=jdbc:mysql://localhost:3306/nip?useSSL=false
spring.datasource.username=root
spring.datasource.password=ayojava
spring.datasource.validation-query=SELECT 1
spring.datasource.test-on-borrow=true
spring.datasource.test-on-return=true


spring.data.jpa.repositories.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

##spring cloud setting
#cloud.aws.credentials.accessKey=
#cloud.aws.credentials.secretKey=
cloud.aws.credentials.instanceProfile=true
#cloud.aws.region.auto=true
cloud.aws.region.static=eu-west-1



nip.senderBankCode=999157
nip.dateTimeFormat=yyMMddHHmmss
nip.sessionIdLength=12
nip.ssmPrivateKeyPath=ssm/ga_private_key.key
nip.ssmPublicKeyPath=ssm/nibss_public_key.key
nip.ssmPasswordKey=techonodevInnovate

#wait time in milliseconds before we send a tsq
nip.tsqWaitTime = 60000

#ignore NIBSS encryption so that we can test for NIP Inward, should be set to FALSE in production
nip.ignoreEncryption= true 


nip.bankUrl=http://localhost:7222

#wait time in milliseconds before we send a tsq
nip.tsqWaitTime = 60000
