//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.12.13 at 05:12:39 PM CAT 
//


package com.globalaccelerex.nipmiddleware.payload.nip.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.globalaccelerex.nipmiddleware.payload.nip package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Accountblock_QNAME = new QName("http://core.nip.nibss/", "accountblock");
    private final static QName _AccountblockResponse_QNAME = new QName("http://core.nip.nibss/", "accountblockResponse");
    private final static QName _Accountunblock_QNAME = new QName("http://core.nip.nibss/", "accountunblock");
    private final static QName _AccountunblockResponse_QNAME = new QName("http://core.nip.nibss/", "accountunblockResponse");
    private final static QName _AdjustNIPSettings_QNAME = new QName("http://core.nip.nibss/", "adjustNIPSettings");
    private final static QName _AdjustNIPSettingsResponse_QNAME = new QName("http://core.nip.nibss/", "adjustNIPSettingsResponse");
    private final static QName _Amountblock_QNAME = new QName("http://core.nip.nibss/", "amountblock");
    private final static QName _AmountblockResponse_QNAME = new QName("http://core.nip.nibss/", "amountblockResponse");
    private final static QName _Amountunblock_QNAME = new QName("http://core.nip.nibss/", "amountunblock");
    private final static QName _AmountunblockResponse_QNAME = new QName("http://core.nip.nibss/", "amountunblockResponse");
    private final static QName _Balanceenquiry_QNAME = new QName("http://core.nip.nibss/", "balanceenquiry");
    private final static QName _BalanceenquiryResponse_QNAME = new QName("http://core.nip.nibss/", "balanceenquiryResponse");
    private final static QName _Financialinstitutionlist_QNAME = new QName("http://core.nip.nibss/", "financialinstitutionlist");
    private final static QName _FinancialinstitutionlistResponse_QNAME = new QName("http://core.nip.nibss/", "financialinstitutionlistResponse");
    private final static QName _Ftackcreditrequest_QNAME = new QName("http://core.nip.nibss/", "ftackcreditrequest");
    private final static QName _FtackcreditrequestResponse_QNAME = new QName("http://core.nip.nibss/", "ftackcreditrequestResponse");
    private final static QName _FundtransferAdviceDc_QNAME = new QName("http://core.nip.nibss/", "fundtransferAdvice_dc");
    private final static QName _FundtransferAdviceDcResponse_QNAME = new QName("http://core.nip.nibss/", "fundtransferAdvice_dcResponse");
    private final static QName _FundtransferAdviceDd_QNAME = new QName("http://core.nip.nibss/", "fundtransferAdvice_dd");
    private final static QName _FundtransferAdviceDdResponse_QNAME = new QName("http://core.nip.nibss/", "fundtransferAdvice_ddResponse");
    private final static QName _FundtransfersingleitemDc_QNAME = new QName("http://core.nip.nibss/", "fundtransfersingleitem_dc");
    private final static QName _FundtransfersingleitemDcResponse_QNAME = new QName("http://core.nip.nibss/", "fundtransfersingleitem_dcResponse");
    private final static QName _FundtransfersingleitemDd_QNAME = new QName("http://core.nip.nibss/", "fundtransfersingleitem_dd");
    private final static QName _FundtransfersingleitemDdResponse_QNAME = new QName("http://core.nip.nibss/", "fundtransfersingleitem_ddResponse");
    private final static QName _Mandateadvice_QNAME = new QName("http://core.nip.nibss/", "mandateadvice");
    private final static QName _MandateadviceResponse_QNAME = new QName("http://core.nip.nibss/", "mandateadviceResponse");
    private final static QName _Nameenquirysingleitem_QNAME = new QName("http://core.nip.nibss/", "nameenquirysingleitem");
    private final static QName _NameenquirysingleitemResponse_QNAME = new QName("http://core.nip.nibss/", "nameenquirysingleitemResponse");
    private final static QName _PrivateAdjustmentOfSettings_QNAME = new QName("http://core.nip.nibss/", "privateAdjustmentOfSettings");
    private final static QName _PrivateAdjustmentOfSettingsResponse_QNAME = new QName("http://core.nip.nibss/", "privateAdjustmentOfSettingsResponse");
    private final static QName _Txnstatusquerysingleitem_QNAME = new QName("http://core.nip.nibss/", "txnstatusquerysingleitem");
    private final static QName _TxnstatusquerysingleitemResponse_QNAME = new QName("http://core.nip.nibss/", "txnstatusquerysingleitemResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.globalaccelerex.nipmiddleware.payload.nip
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accountblock }
     * 
     */
    public Accountblock createAccountblock() {
        return new Accountblock();
    }

    /**
     * Create an instance of {@link AccountblockResponse }
     * 
     */
    public AccountblockResponse createAccountblockResponse() {
        return new AccountblockResponse();
    }

    /**
     * Create an instance of {@link Accountunblock }
     * 
     */
    public Accountunblock createAccountunblock() {
        return new Accountunblock();
    }

    /**
     * Create an instance of {@link AccountunblockResponse }
     * 
     */
    public AccountunblockResponse createAccountunblockResponse() {
        return new AccountunblockResponse();
    }

    /**
     * Create an instance of {@link AdjustNIPSettings }
     * 
     */
    public AdjustNIPSettings createAdjustNIPSettings() {
        return new AdjustNIPSettings();
    }

    /**
     * Create an instance of {@link AdjustNIPSettingsResponse }
     * 
     */
    public AdjustNIPSettingsResponse createAdjustNIPSettingsResponse() {
        return new AdjustNIPSettingsResponse();
    }

    /**
     * Create an instance of {@link Amountblock }
     * 
     */
    public Amountblock createAmountblock() {
        return new Amountblock();
    }

    /**
     * Create an instance of {@link AmountblockResponse }
     * 
     */
    public AmountblockResponse createAmountblockResponse() {
        return new AmountblockResponse();
    }

    /**
     * Create an instance of {@link Amountunblock }
     * 
     */
    public Amountunblock createAmountunblock() {
        return new Amountunblock();
    }

    /**
     * Create an instance of {@link AmountunblockResponse }
     * 
     */
    public AmountunblockResponse createAmountunblockResponse() {
        return new AmountunblockResponse();
    }

    /**
     * Create an instance of {@link Balanceenquiry }
     * 
     */
    public Balanceenquiry createBalanceenquiry() {
        return new Balanceenquiry();
    }

    /**
     * Create an instance of {@link BalanceenquiryResponse }
     * 
     */
    public BalanceenquiryResponse createBalanceenquiryResponse() {
        return new BalanceenquiryResponse();
    }

    /**
     * Create an instance of {@link Financialinstitutionlist }
     * 
     */
    public Financialinstitutionlist createFinancialinstitutionlist() {
        return new Financialinstitutionlist();
    }

    /**
     * Create an instance of {@link FinancialinstitutionlistResponse }
     * 
     */
    public FinancialinstitutionlistResponse createFinancialinstitutionlistResponse() {
        return new FinancialinstitutionlistResponse();
    }

    /**
     * Create an instance of {@link Ftackcreditrequest }
     * 
     */
    public Ftackcreditrequest createFtackcreditrequest() {
        return new Ftackcreditrequest();
    }

    /**
     * Create an instance of {@link FtackcreditrequestResponse }
     * 
     */
    public FtackcreditrequestResponse createFtackcreditrequestResponse() {
        return new FtackcreditrequestResponse();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDc }
     * 
     */
    public FundtransferAdviceDc createFundtransferAdviceDc() {
        return new FundtransferAdviceDc();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDcResponse }
     * 
     */
    public FundtransferAdviceDcResponse createFundtransferAdviceDcResponse() {
        return new FundtransferAdviceDcResponse();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDd }
     * 
     */
    public FundtransferAdviceDd createFundtransferAdviceDd() {
        return new FundtransferAdviceDd();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDdResponse }
     * 
     */
    public FundtransferAdviceDdResponse createFundtransferAdviceDdResponse() {
        return new FundtransferAdviceDdResponse();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDc }
     * 
     */
    public FundtransfersingleitemDc createFundtransfersingleitemDc() {
        return new FundtransfersingleitemDc();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDcResponse }
     * 
     */
    public FundtransfersingleitemDcResponse createFundtransfersingleitemDcResponse() {
        return new FundtransfersingleitemDcResponse();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDd }
     * 
     */
    public FundtransfersingleitemDd createFundtransfersingleitemDd() {
        return new FundtransfersingleitemDd();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDdResponse }
     * 
     */
    public FundtransfersingleitemDdResponse createFundtransfersingleitemDdResponse() {
        return new FundtransfersingleitemDdResponse();
    }

    /**
     * Create an instance of {@link Mandateadvice }
     * 
     */
    public Mandateadvice createMandateadvice() {
        return new Mandateadvice();
    }

    /**
     * Create an instance of {@link MandateadviceResponse }
     * 
     */
    public MandateadviceResponse createMandateadviceResponse() {
        return new MandateadviceResponse();
    }

    /**
     * Create an instance of {@link Nameenquirysingleitem }
     * 
     */
    public Nameenquirysingleitem createNameenquirysingleitem() {
        return new Nameenquirysingleitem();
    }

    /**
     * Create an instance of {@link NameenquirysingleitemResponse }
     * 
     */
    public NameenquirysingleitemResponse createNameenquirysingleitemResponse() {
        return new NameenquirysingleitemResponse();
    }

    /**
     * Create an instance of {@link PrivateAdjustmentOfSettings }
     * 
     */
    public PrivateAdjustmentOfSettings createPrivateAdjustmentOfSettings() {
        return new PrivateAdjustmentOfSettings();
    }

    /**
     * Create an instance of {@link PrivateAdjustmentOfSettingsResponse }
     * 
     */
    public PrivateAdjustmentOfSettingsResponse createPrivateAdjustmentOfSettingsResponse() {
        return new PrivateAdjustmentOfSettingsResponse();
    }

    /**
     * Create an instance of {@link Txnstatusquerysingleitem }
     * 
     */
    public Txnstatusquerysingleitem createTxnstatusquerysingleitem() {
        return new Txnstatusquerysingleitem();
    }

    /**
     * Create an instance of {@link TxnstatusquerysingleitemResponse }
     * 
     */
    public TxnstatusquerysingleitemResponse createTxnstatusquerysingleitemResponse() {
        return new TxnstatusquerysingleitemResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Accountblock }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Accountblock }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "accountblock")
    public JAXBElement<Accountblock> createAccountblock(Accountblock value) {
        return new JAXBElement<Accountblock>(_Accountblock_QNAME, Accountblock.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountblockResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountblockResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "accountblockResponse")
    public JAXBElement<AccountblockResponse> createAccountblockResponse(AccountblockResponse value) {
        return new JAXBElement<AccountblockResponse>(_AccountblockResponse_QNAME, AccountblockResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Accountunblock }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Accountunblock }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "accountunblock")
    public JAXBElement<Accountunblock> createAccountunblock(Accountunblock value) {
        return new JAXBElement<Accountunblock>(_Accountunblock_QNAME, Accountunblock.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountunblockResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountunblockResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "accountunblockResponse")
    public JAXBElement<AccountunblockResponse> createAccountunblockResponse(AccountunblockResponse value) {
        return new JAXBElement<AccountunblockResponse>(_AccountunblockResponse_QNAME, AccountunblockResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdjustNIPSettings }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AdjustNIPSettings }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "adjustNIPSettings")
    public JAXBElement<AdjustNIPSettings> createAdjustNIPSettings(AdjustNIPSettings value) {
        return new JAXBElement<AdjustNIPSettings>(_AdjustNIPSettings_QNAME, AdjustNIPSettings.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdjustNIPSettingsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AdjustNIPSettingsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "adjustNIPSettingsResponse")
    public JAXBElement<AdjustNIPSettingsResponse> createAdjustNIPSettingsResponse(AdjustNIPSettingsResponse value) {
        return new JAXBElement<AdjustNIPSettingsResponse>(_AdjustNIPSettingsResponse_QNAME, AdjustNIPSettingsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amountblock }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Amountblock }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "amountblock")
    public JAXBElement<Amountblock> createAmountblock(Amountblock value) {
        return new JAXBElement<Amountblock>(_Amountblock_QNAME, Amountblock.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountblockResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmountblockResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "amountblockResponse")
    public JAXBElement<AmountblockResponse> createAmountblockResponse(AmountblockResponse value) {
        return new JAXBElement<AmountblockResponse>(_AmountblockResponse_QNAME, AmountblockResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Amountunblock }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Amountunblock }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "amountunblock")
    public JAXBElement<Amountunblock> createAmountunblock(Amountunblock value) {
        return new JAXBElement<Amountunblock>(_Amountunblock_QNAME, Amountunblock.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountunblockResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmountunblockResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "amountunblockResponse")
    public JAXBElement<AmountunblockResponse> createAmountunblockResponse(AmountunblockResponse value) {
        return new JAXBElement<AmountunblockResponse>(_AmountunblockResponse_QNAME, AmountunblockResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Balanceenquiry }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Balanceenquiry }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "balanceenquiry")
    public JAXBElement<Balanceenquiry> createBalanceenquiry(Balanceenquiry value) {
        return new JAXBElement<Balanceenquiry>(_Balanceenquiry_QNAME, Balanceenquiry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalanceenquiryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BalanceenquiryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "balanceenquiryResponse")
    public JAXBElement<BalanceenquiryResponse> createBalanceenquiryResponse(BalanceenquiryResponse value) {
        return new JAXBElement<BalanceenquiryResponse>(_BalanceenquiryResponse_QNAME, BalanceenquiryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Financialinstitutionlist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Financialinstitutionlist }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "financialinstitutionlist")
    public JAXBElement<Financialinstitutionlist> createFinancialinstitutionlist(Financialinstitutionlist value) {
        return new JAXBElement<Financialinstitutionlist>(_Financialinstitutionlist_QNAME, Financialinstitutionlist.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FinancialinstitutionlistResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FinancialinstitutionlistResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "financialinstitutionlistResponse")
    public JAXBElement<FinancialinstitutionlistResponse> createFinancialinstitutionlistResponse(FinancialinstitutionlistResponse value) {
        return new JAXBElement<FinancialinstitutionlistResponse>(_FinancialinstitutionlistResponse_QNAME, FinancialinstitutionlistResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ftackcreditrequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Ftackcreditrequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "ftackcreditrequest")
    public JAXBElement<Ftackcreditrequest> createFtackcreditrequest(Ftackcreditrequest value) {
        return new JAXBElement<Ftackcreditrequest>(_Ftackcreditrequest_QNAME, Ftackcreditrequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FtackcreditrequestResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FtackcreditrequestResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "ftackcreditrequestResponse")
    public JAXBElement<FtackcreditrequestResponse> createFtackcreditrequestResponse(FtackcreditrequestResponse value) {
        return new JAXBElement<FtackcreditrequestResponse>(_FtackcreditrequestResponse_QNAME, FtackcreditrequestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDc }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDc }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransferAdvice_dc")
    public JAXBElement<FundtransferAdviceDc> createFundtransferAdviceDc(FundtransferAdviceDc value) {
        return new JAXBElement<FundtransferAdviceDc>(_FundtransferAdviceDc_QNAME, FundtransferAdviceDc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDcResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDcResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransferAdvice_dcResponse")
    public JAXBElement<FundtransferAdviceDcResponse> createFundtransferAdviceDcResponse(FundtransferAdviceDcResponse value) {
        return new JAXBElement<FundtransferAdviceDcResponse>(_FundtransferAdviceDcResponse_QNAME, FundtransferAdviceDcResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDd }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDd }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransferAdvice_dd")
    public JAXBElement<FundtransferAdviceDd> createFundtransferAdviceDd(FundtransferAdviceDd value) {
        return new JAXBElement<FundtransferAdviceDd>(_FundtransferAdviceDd_QNAME, FundtransferAdviceDd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDdResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransferAdviceDdResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransferAdvice_ddResponse")
    public JAXBElement<FundtransferAdviceDdResponse> createFundtransferAdviceDdResponse(FundtransferAdviceDdResponse value) {
        return new JAXBElement<FundtransferAdviceDdResponse>(_FundtransferAdviceDdResponse_QNAME, FundtransferAdviceDdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDc }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDc }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransfersingleitem_dc")
    public JAXBElement<FundtransfersingleitemDc> createFundtransfersingleitemDc(FundtransfersingleitemDc value) {
        return new JAXBElement<FundtransfersingleitemDc>(_FundtransfersingleitemDc_QNAME, FundtransfersingleitemDc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDcResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDcResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransfersingleitem_dcResponse")
    public JAXBElement<FundtransfersingleitemDcResponse> createFundtransfersingleitemDcResponse(FundtransfersingleitemDcResponse value) {
        return new JAXBElement<FundtransfersingleitemDcResponse>(_FundtransfersingleitemDcResponse_QNAME, FundtransfersingleitemDcResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDd }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDd }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransfersingleitem_dd")
    public JAXBElement<FundtransfersingleitemDd> createFundtransfersingleitemDd(FundtransfersingleitemDd value) {
        return new JAXBElement<FundtransfersingleitemDd>(_FundtransfersingleitemDd_QNAME, FundtransfersingleitemDd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDdResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundtransfersingleitemDdResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "fundtransfersingleitem_ddResponse")
    public JAXBElement<FundtransfersingleitemDdResponse> createFundtransfersingleitemDdResponse(FundtransfersingleitemDdResponse value) {
        return new JAXBElement<FundtransfersingleitemDdResponse>(_FundtransfersingleitemDdResponse_QNAME, FundtransfersingleitemDdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mandateadvice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Mandateadvice }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "mandateadvice")
    public JAXBElement<Mandateadvice> createMandateadvice(Mandateadvice value) {
        return new JAXBElement<Mandateadvice>(_Mandateadvice_QNAME, Mandateadvice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MandateadviceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MandateadviceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "mandateadviceResponse")
    public JAXBElement<MandateadviceResponse> createMandateadviceResponse(MandateadviceResponse value) {
        return new JAXBElement<MandateadviceResponse>(_MandateadviceResponse_QNAME, MandateadviceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Nameenquirysingleitem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Nameenquirysingleitem }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "nameenquirysingleitem")
    public JAXBElement<Nameenquirysingleitem> createNameenquirysingleitem(Nameenquirysingleitem value) {
        return new JAXBElement<Nameenquirysingleitem>(_Nameenquirysingleitem_QNAME, Nameenquirysingleitem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameenquirysingleitemResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NameenquirysingleitemResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "nameenquirysingleitemResponse")
    public JAXBElement<NameenquirysingleitemResponse> createNameenquirysingleitemResponse(NameenquirysingleitemResponse value) {
        return new JAXBElement<NameenquirysingleitemResponse>(_NameenquirysingleitemResponse_QNAME, NameenquirysingleitemResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivateAdjustmentOfSettings }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrivateAdjustmentOfSettings }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "privateAdjustmentOfSettings")
    public JAXBElement<PrivateAdjustmentOfSettings> createPrivateAdjustmentOfSettings(PrivateAdjustmentOfSettings value) {
        return new JAXBElement<PrivateAdjustmentOfSettings>(_PrivateAdjustmentOfSettings_QNAME, PrivateAdjustmentOfSettings.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivateAdjustmentOfSettingsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrivateAdjustmentOfSettingsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "privateAdjustmentOfSettingsResponse")
    public JAXBElement<PrivateAdjustmentOfSettingsResponse> createPrivateAdjustmentOfSettingsResponse(PrivateAdjustmentOfSettingsResponse value) {
        return new JAXBElement<PrivateAdjustmentOfSettingsResponse>(_PrivateAdjustmentOfSettingsResponse_QNAME, PrivateAdjustmentOfSettingsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Txnstatusquerysingleitem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Txnstatusquerysingleitem }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "txnstatusquerysingleitem")
    public JAXBElement<Txnstatusquerysingleitem> createTxnstatusquerysingleitem(Txnstatusquerysingleitem value) {
        return new JAXBElement<Txnstatusquerysingleitem>(_Txnstatusquerysingleitem_QNAME, Txnstatusquerysingleitem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TxnstatusquerysingleitemResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TxnstatusquerysingleitemResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://core.nip.nibss/", name = "txnstatusquerysingleitemResponse")
    public JAXBElement<TxnstatusquerysingleitemResponse> createTxnstatusquerysingleitemResponse(TxnstatusquerysingleitemResponse value) {
        return new JAXBElement<TxnstatusquerysingleitemResponse>(_TxnstatusquerysingleitemResponse_QNAME, TxnstatusquerysingleitemResponse.class, null, value);
    }

}
