//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.12.13 at 05:12:39 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://core.nip.nibss/")
package com.globalaccelerex.nipmiddleware.payload.nip.ws;
